version: "3.8"
services: 
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
     - 8080:80
    volumes:
      - ./app:/var/www/html
      - ./config:/usr/local/etc/php

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-datavolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  html: {}
  my-datavolume:


    